// 100 Categories for Eyes Optical Management System
// Helper function to generate slug
const generateSlug = (name) => {
  return name.toLowerCase().replace(/\s+/g, '-').replace(/[^\w\-]+/g, '');
};

// Generate categories with slugs
const categoriesData = [
  { name: 'Eyeglasses', description: 'Prescription and fashion eyeglasses' },
  { name: 'Sunglasses', description: 'UV protection sunglasses' },
  { name: 'Contact Lenses', description: 'Daily and monthly contact lenses' },
  { name: 'Reading Glasses', description: 'Ready-made reading glasses' },
  { name: 'Computer Glasses', description: 'Blue light filtering glasses' },
  { name: 'Progressive Lenses', description: 'Multifocal progressive lenses' },
  { name: 'Bifocal Prescription Lenses', description: 'Bifocal prescription lenses' },
  { name: 'Photochromic Lenses', description: 'Light-adaptive lenses' },
  { name: 'Polarized Lenses', description: 'Polarized sunglasses' },
  { name: 'Anti-Reflective Coating', description: 'AR coating for lenses' },
  { name: 'Blue Light Blocking', description: 'Blue light filtering technology' },
  { name: 'High Index Lenses', description: 'Thin and lightweight lenses' },
  { name: 'Polycarbonate Lenses', description: 'Impact-resistant lenses' },
  { name: 'Trivex Lenses', description: 'Lightweight and durable lenses' },
  { name: 'Aspheric Lenses', description: 'Thinner and flatter lenses' },
  { name: 'Kids Eyeglasses', description: 'Durable frames for children' },
  { name: 'Sports Eyewear', description: 'Protective sports glasses' },
  { name: 'Safety Glasses', description: 'Industrial safety eyewear' },
  { name: 'Designer Frames', description: 'Premium designer eyewear' },
  { name: 'Budget Frames', description: 'Affordable eyewear options' },
  { name: 'Titanium Frames', description: 'Lightweight titanium frames' },
  { name: 'Acetate Frames', description: 'Classic acetate frames' },
  { name: 'Metal Frames', description: 'Sturdy metal frame options' },
  { name: 'Rimless Frames', description: 'Minimalist rimless designs' },
  { name: 'Semi-Rimless Frames', description: 'Semi-rimless frame styles' },
  { name: 'Full-Rim Frames', description: 'Traditional full-rim frames' },
  { name: 'Oversized Frames', description: 'Large statement frames' },
  { name: 'Round Frames', description: 'Classic round frame shapes' },
  { name: 'Square Frames', description: 'Modern square frame designs' },
  { name: 'Aviator Frames', description: 'Classic aviator style' },
  { name: 'Cat-Eye Frames', description: 'Vintage cat-eye designs' },
  { name: 'Wayfarer Frames', description: 'Iconic wayfarer style' },
  { name: 'Browline Frames', description: 'Retro browline frames' },
  { name: 'Oval Frames', description: 'Soft oval frame shapes' },
  { name: 'Rectangle Frames', description: 'Geometric rectangle frames' },
  { name: 'Clubmaster Frames', description: 'Classic clubmaster style' },
  { name: 'Pilot Frames', description: 'Aviation-inspired frames' },
  { name: 'Vintage Frames', description: 'Retro vintage designs' },
  { name: 'Modern Frames', description: 'Contemporary frame styles' },
  { name: 'Minimalist Frames', description: 'Simple minimalist designs' },
  { name: 'Bold Frames', description: 'Statement bold frame styles' },
  { name: 'Colorful Frames', description: 'Vibrant colored frames' },
  { name: 'Neutral Frames', description: 'Classic neutral colors' },
  { name: 'Gradient Lenses', description: 'Gradient tinted lenses' },
  { name: 'Mirror Lenses', description: 'Reflective mirror lenses' },
  { name: 'Tinted Lenses', description: 'Custom tinted lenses' },
  { name: 'Clear Lenses', description: 'Standard clear lenses' },
  { name: 'Transition Lenses', description: 'Photochromic transition lenses' },
  { name: 'Single Vision Lenses', description: 'Standard single vision' },
  { name: 'Multifocal Lenses', description: 'Progressive multifocal options' },
  { name: 'Traditional Bifocal Lenses', description: 'Traditional bifocal lenses' },
  { name: 'Trifocal Lenses', description: 'Three-zone trifocal lenses' },
  { name: 'Occupational Lenses', description: 'Specialized work lenses' },
  { name: 'Driving Lenses', description: 'Optimized for driving' },
  { name: 'Gaming Glasses', description: 'Blue light for gaming' },
  { name: 'Night Driving Glasses', description: 'Anti-glare night driving' },
  { name: 'Swimming Goggles', description: 'Prescription swimming goggles' },
  { name: 'Ski Goggles', description: 'Prescription ski goggles' },
  { name: 'Cycling Glasses', description: 'Sports cycling eyewear' },
  { name: 'Running Glasses', description: 'Active running eyewear' },
  { name: 'Golf Glasses', description: 'Specialized golf eyewear' },
  { name: 'Fishing Glasses', description: 'Polarized fishing glasses' },
  { name: 'Hunting Glasses', description: 'Specialized hunting eyewear' },
  { name: 'Tactical Glasses', description: 'Military-style tactical frames' },
  { name: 'Fashion Sunglasses', description: 'Trendy fashion sunglasses' },
  { name: 'Luxury Sunglasses', description: 'Premium luxury brands' },
  { name: 'Budget Sunglasses', description: 'Affordable sunglasses' },
  { name: 'Vintage Sunglasses', description: 'Retro sunglass styles' },
  { name: 'Designer Sunglasses', description: 'High-end designer brands' },
  { name: 'Sports Sunglasses', description: 'Performance sports sunglasses' },
  { name: 'Wrap-Around Sunglasses', description: 'Full coverage wrap style' },
  { name: 'Oversized Sunglasses', description: 'Large statement sunglasses' },
  { name: 'Small Frame Sunglasses', description: 'Petite frame sunglasses' },
  { name: 'Unisex Sunglasses', description: 'Universal fit sunglasses' },
  { name: 'Men\'s Sunglasses', description: 'Men\'s specific designs' },
  { name: 'Women\'s Sunglasses', description: 'Women\'s specific designs' },
  { name: 'Kids Sunglasses', description: 'Children\'s sunglasses' },
  { name: 'Teen Sunglasses', description: 'Teen-friendly styles' },
  { name: 'Senior Eyewear', description: 'Comfort-focused for seniors' },
  { name: 'Low Vision Aids', description: 'Magnification devices' },
  { name: 'Telescopic Glasses', description: 'Vision enhancement devices' },
  { name: 'Prism Lenses', description: 'Prism correction lenses' },
  { name: 'Orthokeratology', description: 'Ortho-k contact lenses' },
  { name: 'Daily Contacts', description: 'Daily disposable contacts' },
  { name: 'Monthly Contacts', description: 'Monthly replacement contacts' },
  { name: 'Bi-Weekly Contacts', description: 'Two-week replacement contacts' },
  { name: 'Toric Contacts', description: 'Astigmatism correction contacts' },
  { name: 'Multifocal Contacts', description: 'Presbyopia contact lenses' },
  { name: 'Colored Contacts', description: 'Cosmetic colored contacts' },
  { name: 'Scleral Lenses', description: 'Large diameter scleral lenses' },
  { name: 'RGP Lenses', description: 'Rigid gas permeable lenses' },
  { name: 'Soft Contacts', description: 'Comfortable soft lenses' },
  { name: 'Extended Wear Contacts', description: 'Overnight wear contacts' },
  { name: 'Contact Lens Solutions', description: 'Cleaning and storage solutions' },
  { name: 'Contact Lens Cases', description: 'Storage cases and accessories' },
  { name: 'Eye Drops', description: 'Lubricating eye drops' },
  { name: 'Lens Cleaners', description: 'Lens cleaning solutions' },
  { name: 'Microfiber Cloths', description: 'Lens cleaning cloths' },
  { name: 'Frame Repair Kits', description: 'DIY frame repair tools' },
  { name: 'Nose Pads', description: 'Replacement nose pads' },
  { name: 'Temple Tips', description: 'Ear piece replacements' },
  { name: 'Screws and Hardware', description: 'Frame hardware components' },
  { name: 'Eyewear Accessories', description: 'Cases, chains, and more' },
  { name: 'Prescription Lenses Only', description: 'Lens replacement service' },
  { name: 'Frame Only', description: 'Frames without lenses' }
];

// Generate slugs for all categories and export
export const categories = categoriesData.map(cat => ({
  ...cat,
  slug: generateSlug(cat.name)
}));

